# Generated by Django 5.1.2 on 2025-03-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
    ]
