# Generated by Django 5.1.4 on 2025-03-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.address'),
        ),
    ]
